# Name of your application. Used to uniquely configure containers.
service: rails_reservation

# Name of the container image (use your-user/app-name on external registries).
image: kokihiru/rails_reservation

# Deploy to these servers.
servers:
  web:
    - 162.43.77.16

proxy:
  host: reservation.ruu-dev.com
  app_port: 3000 # Railsの内部ポート（3000が標準）
  ssl: true # 追加
  forward_headers: true
  response_timeout: 300
  buffering:
    responses: false

# Where you keep your container images.
registry:
  # Alternatives: hub.docker.com / registry.digitalocean.com / ghcr.io / ...
  server: index.docker.io

  # Needed for authenticated registries.
  username: kokihiru

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "rails_reservation_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
